### ISSUE TITLE
egress partners

### ISSUE THREAD

**Issue by usrdev** [packethost/docs#100]
Wasabi | BackBlaze. 

[05-storage/02-zero-egress-partners.md](https://github.com/packethost/docs/blob/master/products/05-storage/02-zero-egress-partners.md)

**Comment by usrdev** [comment]
https://github.com/packethost/docs/blob/moupdates110419/products/storage/zero-egress.md

**Comment by zalkar-z** [comment]
@usrdev [05-storage/03-zero-egress-partners.md](https://github.com/packethost/docs/blob/master/products/05-storage/03-zero-egress-partners.md)

**Comment by usrdev** [comment]
done.
