### ISSUE TITLE
Kubernetes KB Article

### ISSUE THREAD

**Issue by jmarhee** [packethost/docs#156]
I'm not sure where this is managed, or if it will be moved here, but:

https://support.packet.com/kb/articles/kubernetes?utm_content=105968868&utm_medium=social&utm_source=twitter&hss_channel=tw-2586796098

only references the `FlexVolume` plugin, which is, at this point, somewhat out-of-date, so I'd like to request the addition under "Plugins and Official Integrations" include:

https://github.com/packethost/packet-ccm
and
https://github.com/packethost/csi-packet (with the note that CSI is supported in K8s 1.13+)

**Comment by jacobsmith928** [comment]
@jmarhee I'm sure @usrdev can advise. Probably that old article needs to go away and be replaced with a lovely new guide.

**Comment by usrdev** [comment]
moving to @jmarhee he has some ideas here. :)

**Comment by usrdev** [comment]
the DeskPro article is outdated. and will not be migrated.

**Comment by jmarhee** [comment]
I opened PR #180 but think I may be missing a few solutions/partners worth mentioning among the commercial solutions, and some community-supported solutions. Let me know if this is the case, but this is basically an updated (removed dead links, added new integrations section, etc.) version of the old KB article.

**Comment by jmarhee** [comment]
@vielmetti also; is there anyone/any other projects/resources I should be sure to include in #180 ?

**Comment by usrdev** [comment]
i merged this. however, feel free to update as you find more items to include. but for now, i'l call this issue closed.
