### ISSUE TITLE
Add Drone configuration for CI

### ISSUE THREAD

**Issue by vielmetti** [packethost/docs#2]
Add a simple Drone Cloud configuration to this repo, so that we have tests.

As an example, this might include

* lint for the Markdown files, so we catch structural problems fast
* grammar/style/spelling checks for Markdown files
* production of PDF output or other print-ready or ebook-ready formats (with Pandoc)

As a start I'm thinking we set up just enough so that the README lints clean.

**Comment by zalkar-z** [comment]
@vielmetti so I am using https://github.com/igorshubovych/markdownlint-cli as a lint to catch structural problems.

For grammar/spelling check - I am thinking about https://www.npmjs.com/package/markdown-spellcheck but now quite sure yet. Do you have any tools you've used or would recommend for markdown grammar/spelling check?

Thanks!

**Comment by vielmetti** [comment]
I will look - there should be one that's driven by a style guide, I can't recall the name but it caught things like certain uses of language that had overtones that were inappropriate.

**Comment by vielmetti** [comment]
@zalkar-z Let's try with the `npmjs` package you mention, and see how it goes and what it catches.

**Comment by deitch** [comment]
I personally have a preference for "bare" CI-as-a-Service files, just wrapping commands in Makefiles. That makes it easier to run things locally or in CI the same, and thus see what is happening (faster cycle time).

For example, [look at this PR I just opened for packngo](https://github.com/packethost/packngo/pull/149). The commands to run lint on the Golang files are all in the makefile, and can be run locally or in a docker container; the `.drone.yml` file just wraps it.

**Comment by vielmetti** [comment]
Oooh, I like "make lint" as a Makefile target, and then Drone just wrapping that. Nice.

**Comment by zalkar-z** [comment]
@deitch sounds like a great idea. Let me check this out. Thanks!
