### ISSUE TITLE
Double Check User State Article

### ISSUE THREAD

**Issue by Naji-F-Pride** [packethost/docs#260]
I'm not sure the description of how to use the user state feature makes sense. We should double check this article to make sure it works.

**Comment by zalkar-z** [comment]
@Naji-F-Pride can you please link the doc here?

**Comment by usrdev** [comment]
checking with folks. will report back.

**Comment by enkelprifti98** [comment]
User state was updated with PR #353 .

**Comment by usrdev** [comment]
thank you @enkelprifti98 closing this out now.
