### ISSUE TITLE
"termination_time" parameter for CI jobs

### ISSUE THREAD

**Issue by vielmetti** [packethost/docs#3]
It's possible to configure a server or batch of servers to be automatically deleted after provisioning at a specific time by setting the "termination_time" parameter. There is a brief mention of this in the spot market page currently at https://support.packet.com/kb/articles/spot-market

The observation is that this would be a tremendously useful parameter to add for folks doing batch deployments for short-lived CI runs, and we should document this with an eye towards those applications.

**Comment by vielmetti** [comment]
@Naji-F-Pride @zalkar-z 

I'd look at https://github.com/packethost/docs/blob/master/products/servers/deployment-options/spot-market.md first and would see if there could be another paragraph in there of description. Let me draft a PR.

**Comment by vielmetti** [comment]
PR in #60 please look?

**Comment by zalkar-z** [comment]
Merged. Closing this issue. Thanks @vielmetti @Naji-F-Pride
