### ISSUE TITLE
Custom partitioning and raid 

### ISSUE THREAD

**Issue by vielmetti** [packethost/docs#61]
There's an existing document at 

https://support.packet.com/kb/articles/custom-partitioning-raid

which talks about how to do custom drive partitioning. I'd like to see it expanded out a little bit, with examples targeted at the c2.large.arm (which is the system we are running into needs to get a custom file system on) and examples that include file systems other than ext4 (namely XFS).

**Comment by usrdev** [comment]
this has been updated/merged etc. feel free to submit any additional PRs that you find need updated.
