### ISSUE TITLE
legal-and-compliance/overview.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#67]
[overview.md](https://github.com/packethost/docs/blob/master/products/06-sales-and-support/02-legal-compliance/01-overview.md)

@jacobsmith928 please complete this document as mentioned in the Products Outline doc earlier.

**Comment by usrdev** [comment]
this is done, but not rendering meta. https://github.com/packethost/docs/blob/master/products/06-sales-and-support/02-legal-compliance/01-overview.md

@zalkar-z or maybe someone else can tell me why this is?

**Comment by zalkar-z** [comment]
fixed the metadata issue–rendering on the staging now.
