### ISSUE TITLE
sales-and-support/maintenance-events.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#71]
[maintenance-events.md](https://github.com/packethost/docs/blob/master/products/06-sales-support-and-accounts/03-sales-support/02-maintenance-events.md)

@jacobsmith928 please complete this document as mentioned in the Products Outline doc earlier.

**Comment by Naji-F-Pride** [comment]
Drafted this document and included it in PR 112.

**Comment by zalkar-z** [comment]
done. the document is on the staging now.
