### ISSUE TITLE
sales-and-support/slack.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#72]
[slack.md](https://github.com/packethost/docs/blob/master/products/product-overview/sales-and-support/slack.md)

@jacobsmith928 please complete this document as mentioned in the Products Outline doc earlier.

**Comment by usrdev** [comment]
i do not believe this needs to be written. as it stands sales folks should include the community slack in their chat with companies and also, in our account approval messaging via DeskPro slack community is mentioned. closing.
