### ISSUE TITLE
sales-and-support/pricing-discounts.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#73]
[pricing-discounts.md](https://github.com/packethost/docs/blob/master/products/06-sales-and-support/03-sales-support/03-pricing-discounts.md)

@jacobsmith928 please complete this document as mentioned in the Products Outline doc earlier.

**Comment by usrdev** [comment]
done.

**Comment by zalkar-z** [comment]
neat! maybe put an email at the end where we say "Please contact us to schedule a conversation."?

**Comment by usrdev** [comment]
fixed.
