### ISSUE TITLE
network/basic/standard-ips.md 

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#76]
@usrdev please complete [standard-ips.md](https://github.com/packethost/docs/blob/master/products/network/basic/standard-ips.md) document. Most of the content could be taken out from [elastic-ips.md](https://github.com/packethost/docs/blob/master/products/network/basic/elastic-ips.md) so that the latter focuses solely on elastic IPs.

**Comment by usrdev** [comment]
done.
