### ISSUE TITLE
local-and-global-bgp.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#77]
[local-and-global-bgp.md](https://github.com/packethost/docs/blob/master/products/04-network/03-advanced/02-local-and-global-bgp.md)

This file is too big for its current purpose. Please work on to take out some part of it to our /guides section and link it here. For more info - @jacobsmith928

**Comment by usrdev** [comment]
@Naji-F-Pride can you help condensing this?

**Comment by enkelprifti98** [comment]
This was shortened as of PR #302 .
