### ISSUE TITLE
storage/overview.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#80]
[storage/overview.md](https://github.com/packethost/docs/blob/master/products/05-storage/01-overview.md)

Please, complete this overview document. 
Also, please include some information about [extending blockstorage](https://github.com/packethost/docs/blob/master/products/05-storage/02-blockstorage.md) and link it in the overview.

**Comment by usrdev** [comment]
[PR Submitted & Merged.](https://github.com/packethost/docs/pull/218)

**Comment by usrdev** [comment]
done. http://staging.packet.net/developers/docs/05-storage/01-overview
