### ISSUE TITLE
operating-systems/overview.md

### ISSUE THREAD

**Issue by zalkar-z** [packethost/docs#83]
[operating-systems/overview.md](https://github.com/packethost/docs/blob/master/products/03-servers/04-operating-systems/01-overview.md)

@Naji-F-Pride please complete this document. Also, please provide some links to the information about official OSs on the main website. Reach out to @jacobsmith928 for more info.

**Comment by Naji-F-Pride** [comment]
Added in commit 1554bf5b5438ec8cd308c4c16ab7fa1b264ba774 (apologies for the terrible commit message).

@zalkar-z @usrdev, please review and close if appropriate.

**Comment by usrdev** [comment]
merged. closing out.
