### ISSUE TITLE
Lightbits

### ISSUE THREAD

**Issue by usrdev** [packethost/docs#91]
Create a guide for using Lightbits on our platform. 

a few documents to help: 

https://drive.google.com/file/d/1LEOsE6NBeGse-nahFsEcJR7FEWWXcGW5/view?usp=sharing

https://drive.google.com/file/d/1KuqiJZoyLESWnYyQpRf2c6iVeAdN1qxI/view?usp=sharing

**Comment by usrdev** [comment]
reviewing the pdfs above, there isn't any information really to gather/understand how to deploy this on our platform. i reached out to Chris to see about setting up a session with them, and/or have their team write a guide on how to correctly deploy on our platform. much like that of VIRL, VyOS etc in the past.

**Comment by jacobsmith928** [comment]
I think we  may need to take this down since it only applies if you have access to special Lightbits storage equipment.

**Comment by usrdev** [comment]
closing.
