### ISSUE TITLE
add inventory

### ISSUE THREAD

**Issue by usrdev** [packethost/docs#96]
https://support.packet.com/kb/articles/inventory

**Comment by zalkar-z** [comment]
@usrdev Hi Mo! I think [this](https://github.com/packethost/docs/blob/master/products/03-servers/02-deployment-options/05-capacity-inventory.md) is the doc to go with. Thanks!

**Comment by usrdev** [comment]
> @usrdev Hi Mo! I think [this](https://github.com/packethost/docs/blob/master/products/03-servers/02-deployment-options/05-capacity-inventory.md) is the doc to go with. Thanks!

yep, correct; however my link is to the existing content. just making it easier when i get to this doc. :)

**Comment by usrdev** [comment]
done.
